on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  main-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: echo github_tag=v$(git rev-list --count HEAD) >> $GITHUB_OUTPUT
      - run: zip -r nomi-ceu-modern-${{ steps.version.outputs.github_tag }}.zip overrides manifest.json modlist.json
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.github_tag }}',
              sha: context.sha
            })
      - uses: softprops/action-gh-release@v2
        with:
          files: nomi-ceu-modern-${{ steps.version.outputs.github_tag }}.zip
          tag_name: ${{ steps.version.outputs.github_tag }}
